// Helper to normalize apostrophes (database uses curly ', code uses straight ')
export const normalizeApostrophe = (str) => {
    if (!str) return str;
    return str.replace(/[\u2018\u2019\u201A\u201B\u2032\u2035]/g, "'");
};

// Helper for Topic Mapping (Extracted from SQL)
// Used to strictly filter sub-topics based on main topic selection
export const TOPIC_MAPPING = {
    // Using straight apostrophe for code, but normalize when matching
    "Veriff Doesn't Accept KYC Documents": "KYC_Issue",
    "Waiting For KYC Verification": "KYC_Issue",
    "KYC Verification Delay Issue": "KYC_Issue",
    "KYC Done Yet to Receive FundedNext Account": "KYC_Issue",
    "Eligible for KYC But Pop-Up Missing": "KYC_Issue",
    "Already submitted but Dashboard shows “Verification Required”": "KYC_Issue",
    "TRM Email Issue": "KYC_Issue",
    "AI Interview / HireFlix Issue": "KYC_Issue",
    "Live Interview – No One Joined": "KYC_Issue",
    "Missed Interview Email": "KYC_Issue",
    "Underage": "KYC_Issue",
    "Swift KYC Not Eligible": "KYC_Issue",
    "KYC Eligibility Inquiry": "KYC_Issue",
    "Fundednext Account Query": "Account Related Issue",
    "Did not receive Phase 2 Account": "Account Related Issue",
    "Facing error while trying to sign agreement": "Account Related Issue",
    "Challenge Account Query": "Account Related Issue",
    "Unable to Create an Account": "Account Related Issue",
    "Email already taken during registration": "Account Related Issue",
    "Cannot update information": "Account Related Issue",
    "Wrong Email Used": "Account Related Issue",
    "Email Change": "Account Related Issue",
    "Name Change": "Account Related Issue",
    "Country Change": "Account Related Issue",
    "Account Delete Request": "Account Related Issue",
    "Missing account in breached/inactive section": "Account Related Issue",
    "Account flagged without email": "Account Related Issue",
    "Account Deactivation Due to Abusive Activities": "Account Related Issue",
    "IP/Device Confirmation": "Account Related Issue",
    "Dashboard update delay": "Dashboard Related Issue",
    "Dashboard Access Blocked (Client Internet)": "Dashboard Related Issue",
    "Dashboard Access Blocked (TT Issue)": "Dashboard Related Issue",
    "Account Breach Issue": "Breach Issue",
    "“Undefined” Login Error": "Login_Issue",
    "Login Technical Glitch": "Login_Issue",
    "MT5 Platform Login Issues": "Login_Issue",
    "MT4 Login Issue": "Login_Issue",
    "TradingView login Issue": "Login_Issue",
    "Tradovate login Issue": "Login_Issue",
    "Ninjatrader login issue": "Login_Issue",
    "Competition Login Issue": "Login_Issue",
    "Missing Password Mail": "Password issue",
    "Next Phase Button Missing": "Next Phase Button Missing",
    "Platform Freeze": "Platform Issue",
    "Price/Chart Discrepancy": "Platform Issue",
    "Market Data Delayed Issue": "Platform Issue",
    "Missing Old Chart Data": "Platform Issue",
    "Unable to Use Indicator": "Platform Issue",
    "Unable to Use EA": "Platform Issue",
    "TradingView not available for CFD": "Platform Issue",
    "Crypto Pair Unavailable": "Platform Issue",
    "Crypto Weekend Trading": "Platform Issue",
    "High Spread": "Platform Issue",
    "Unable to Close During News": "Platform Issue",
    "Off-Market Hour Issue": "Platform Issue",
    "Incorrect Trading Cycle": "Trade Issue",
    "Trading Disabled": "Trade Issue",
    "Not Enough Money": "Trade Issue",
    "Pending Order Didn't Execute": "Trade Issue",
    "Trade Closed at Cycle End": "Trade Issue",
    "Trade Disappeared": "Trade Issue",
    "Unauthorized Trade": "Trade Issue",
    "TP Didn't Hit Desired Price": "Trade Issue",
    "Trade Closed Outside Candle (News)": "Trade Issue",
    "Profit Target Reached but Minimum Trading Days Incomplete": "Trade Issue",
    "Minimum Trading Days Confusion": "Trade Issue",
    "Weekend Gap": "Trade Issue",
    "ASK/BID Confusion": "Trade Issue",
    "50 Trades Limit Exceeded": "Trade Issue",
    "Slippage Issue": "Slippage",
    "Regular Slippage": "Slippage",
    "Due to High Lot Size": "Slippage",
    "During News / High Impact": "Slippage",
    "Due to Server Issue": "Slippage",
    "Volume Surge": "Slippage",
    "Midnight Slippage": "Slippage",
    "Swap Charge Confusion": "SWAP",
    "High Processing Fee Complaint": "Commission",
    "Affiliate Issue": "Commission",
    "Affiliate Code Failed": "Commission",
    "Payout On Hold": "Payout related issue",
    "Payout Delay Issue": "Payout related issue",
    "Not Eligible for Payout": "Payout related issue",
    "Payout Discrepancy": "Payout related issue",
    "Invalid Wallet": "Payout related issue",
    "RiseWorks Issue": "Payout related issue",
    "Unable to See Payout Proof": "Payout related issue",
    "Invoice Request": "Payout related issue",
    "TRM Deduction Email": "Payout related issue",
    "Payout from Breached Account": "Payout related issue",
    "Profit Share Below Minimum ($20)": "Payout related issue",
    "ECM Issue": "Payout related issue",
    "Claiming Brand Promise": "Payout related issue",
    "Payout Related Query": "Payout related issue",
    "Reported Late (3+ weeks)": "Payout related issue",
    "Elite Trader Certificate": "Certificate Issue",
    "Payout Certificate": "Certificate Issue",
    "Checking Elite Cert in Wrong Phase": "Certificate Issue",
    "Certificate Name Issue": "Certificate Issue",
    "Asking for Certificate After Phase 2": "Certificate Issue",
    "Leaderboard Error": "Competition Issue",
    "Unhappy with Winner Result": "Competition Issue",
    "Breached Competition Rule": "Competition Issue",
    "Reward Delay": "Competition Issue",
    "Asking Winners Info": "Competition Issue",
    "Registered for Next Month": "Competition Issue",
    "Wants Competition Reset": "Competition Issue",
    "Competition Rule Clarification": "Competition Issue",
    "Unable to register in the Monthly Competition": "Competition Issue",
    "Restricted Country Issue": "Restriction Related Issue",
    "Location Related Issue": "Restriction Related Issue",
    "Concern about EA Rules": "Restriction Related Issue",
    "EA Restriction (cTrader)": "Restriction Related Issue",
    "Abuser Client (Banned)": "Restriction Related Issue",
    "Leverage Reduction": "Restriction Related Issue",
    "Verdict from CPM": "Verdict from different team",
    "Verdict from Trading & Ethics": "Verdict from different team",
    "Verdict from PO": "Verdict from different team",
    "2FA Issue": "Tech Issue",
    "OTP Not Received": "Tech Issue",
    "Balance Mismatch": "Tech Issue",
    "Facing Payment Error": "Other Payment Issues",
    "Payment Method Not Available": "Other Payment Issues",
    "UPI Payment Missing": "Other Payment Issues",
    "Payment Rejected from Client’s End": "Other Payment Issues",
    "Partial Payment Not Possible": "Other Payment Issues",
    "No Payment Found (UPI/Local)": "Other Payment Issues",
    "Unable to Submit Payment Form (TC Pay)": "Other Payment Issues",
    "Account Not Provided Instantly (TC Pay)": "Other Payment Issues",
    "Account Not Provided Instantly (Local)": "Other Payment Issues",
    "Account Not Provided Instantly (Crypto)": "Other Payment Issues",
    "Paid Less Than Needed": "Other Payment Issues",
    "Crypto Payment Not Reflected": "Crypto Payment Isssue",
    "Wrong Network Payment": "Crypto Payment Isssue",
    "Network Not Available": "Crypto Payment Isssue",
    "Crypto Payment Failed (Client Side)": "Crypto Payment Isssue",
    "No Crypto Payment Found": "Crypto Payment Isssue",
    "Double Charged": "Card Payment issue",
    "Refund Delay": "Refund Related Issue",
    "Confirmo Refund Issue": "Refund Related Issue",
    "Coupon Code Not Working": "Coupon Code related issue",
    "Coupon Not Available": "Coupon Code related issue",
    "Forgot to Apply Coupon": "Coupon Code related issue",
    "Looking for coupon code": "Coupon Code related issue",
    "No Personal Coupon": "Coupon Code related issue",
    "Unhappy with Coupon Perks": "Discount related issue",
    "Unsatisfied with Discount": "Discount related issue",
    "Offer Related Query": "Offer Related Query",
    "Halloween Offer Query": "Offer Related Query",
    "Offer related confusion": "Offer Related Query",
    "Giveaway Claim": "Offer Related Query",
    "Giveaway Query": "Offer Related Query",
    "Unhappy Not Winning Giveaway": "Offer Related Query",
    "Missing Free BOGO Account": "Offer Related Query",
    "Asking for BOGO Early": "Offer Related Query",
    "Delay in Receiving Customer Support.": "Random Issues",
    "Subscription Email Issue": "Random Issues",
    "Dispute Related Issue": "Random Issues",
    "Other": "Random Issues",
    "VPS Usage and Replacement Inquiry": "Platform Issue",
    "VPS Change Inquiry": "Platform Issue",
    // "Challenge Rule Clarification" is classified Query-side (see QUERY_TOPIC_MAPPING).
    "Scaling Rule Clarification": "Trade Issue",
    "Reset Eligibility Inquiry (Phase 2)": "Account Related Issue",
    "Dissatisfied with PO Adjustment": "Trade Issue",
    "Adjustment Denied": "Trade Issue",
    "Wrong Account Model Purchase": "Other Payment Issues",

    // FLEX Issues — problems specifically tied to FundedNext Futures FLEX
    // (payment declined for FLEX, coupon not applying to FLEX, FLEX account
    // not provisioned, FLEX dashboard/login glitches, FLEX rule disputes).
    // Main = Sub = "FLEX Issues" by design.
    "FLEX Issues": "FLEX Issues",

    // Additional mappings found in database
    "Funded Account Rules": "Trade Issue",
    "News Trading Allowed": "Trade Issue",
    "News Trading Query": "Trade Issue",
    "Payout Rejected": "Payout related issue",
    "Payout Method": "Payout related issue",
    "Reset Eligibility": "Account Related Issue",
    "Scale-Up Eligibility Inquiry": "Account Related Issue",
    "Maximum Loss Limit": "Trade Issue",
    "Trading Disabled": "Trade Issue",

    // ========== DB sub-topics mapped from n8n prompt (2026-03-31) ==========
    // Account Related
    "2FA Reset": "Tech Issue",
    "Account Access": "Account Related Issue",
    "Account Access Issues": "Account Related Issue",
    "Account Activation": "Account Related Issue",
    "Account Activation Delay": "Account Related Issue",
    "Account Allocation Limits": "Account Related Issue",
    "Account and Drawdown Queries": "Trade Issue",
    "Account Balance Inquiry": "Account Related Issue",
    "Account Ban": "Account Related Issue",
    "Account Buffer Requirements": "Trade Issue",
    "Account Challenge Details": "Account Related Issue",
    "Account Closure": "Account Related Issue",
    "Account Currency and Payout": "Payout related issue",
    "Account Deletion": "Account Related Issue",
    "Account Deletion Request": "Account Related Issue",
    "Account Details Visibility": "Account Related Issue",
    "Account Display Issue": "Dashboard Related Issue",
    "Account Features": "Account Related Issue",
    "Account Fees": "Account Related Issue",
    "Account Funding Delay": "Account Related Issue",
    "Account Inactivity and Deactivation": "Account Related Issue",
    "Account Information Update": "Account Related Issue",
    "Account Integration": "Account Related Issue",
    "Account Issues": "Account Related Issue",
    "Account Limits": "Account Related Issue",
    "Account Limits and Risk Management": "Trade Issue",
    "Account Limits and Trading Rules": "Trade Issue",
    "Account Login Issues": "Login_Issue",
    "Account Loss Limits": "Trade Issue",
    "Account Management": "Account Related Issue",
    "Account Merge": "Account Related Issue",
    "Account Merging": "Account Related Issue",
    "Account Models - Stellar 2 Step Rules": "Account Related Issue",
    "Account Models - Stellar Lite Rules": "Account Related Issue",
    "Account Models and Add-Ons": "Account Related Issue",
    "Account Name Correction / Identity Verification": "Account Related Issue",
    "Account Opening": "Account Related Issue",
    "Account Pause/Unpause": "Account Related Issue",
    "Account Payout Inquiry": "Payout related issue",
    "Account Performance Inquiry": "Account Related Issue",
    "Account Plan Swap": "Account Related Issue",
    "Account Plans Explanation": "Account Related Issue",
    "Account Purchase & Payment": "Other Payment Issues",
    "Account Reactivation and Program Terms": "Account Related Issue",
    "Account Recovery / 2FA Issues": "Tech Issue",
    "Account Related Services": "Account Related Issue",
    "Account Requirements": "Account Related Issue",
    "Account Reset": "Account Related Issue",
    "Account Reset and Fees": "Account Related Issue",
    "Account Reset and Platform Change": "Account Related Issue",
    "Account Restrictions": "Restriction Related Issue",
    "Account Review": "Account Related Issue",
    "Account Rules": "Trade Issue",
    "Account Rules and Limits": "Trade Issue",
    "Account Rules and Payouts": "Payout related issue",
    "Account Rules and Trading Limits": "Trade Issue",
    "Account Services": "Account Related Issue",
    "Account Setup and Access Issues": "Account Related Issue",
    "Account Setup and Trading Process": "Account Related Issue",
    "Account Status and Eligibility": "Account Related Issue",
    "Account Suspension and Loss Calculation": "Account Related Issue",
    "Account Terms and Conditions": "Account Related Issue",
    "Account Type and Add-Ons": "Account Related Issue",
    "Account Types": "Account Related Issue",
    "Account Types and Availability": "Account Related Issue",
    "Account Types and Earnings": "Account Related Issue",
    "Account Types and Fees": "Account Related Issue",
    "Account Types and Rules": "Account Related Issue",
    "Account Types and Trading Instruments": "Account Related Issue",
    "Account Usage": "Account Related Issue",
    "Account Usage & Trading Rules": "Trade Issue",
    "Account Usage and Restrictions": "Restriction Related Issue",
    "Account Validation": "Account Related Issue",
    "Account Verification and Trading Rules": "Account Related Issue",
    "Account Verification Process": "Account Related Issue",
    "Algo Trading and Account Rules": "Restriction Related Issue",
    "Authentication and Transaction Issues": "Tech Issue",
    // BOGO & Offers
    "BOGO Account Eligibility": "Offer Related Query",
    "BOGO Offer Clarification": "Offer Related Query",
    "BOGO Offer Eligibility": "Offer Related Query",
    "BOGO Offer Inquiry": "Offer Related Query",
    "Bonus Payment": "Payout related issue",
    "Bonus Reward Eligibility": "Payout related issue",
    "Certificate Name Change": "Certificate Issue",
    "CFD / Forex": "Platform & Trading",
    "CFD Trading Restrictions": "Restriction Related Issue",
    "Challenge Account": "Account Related Issue",
    "Challenge Account Issue": "Account Related Issue",
    "Challenge Account Trading": "Trade Issue",
    "Challenge Requirements": "Trade Issue",
    "Challenge Rules": "Trade Issue",
    "Challenge Rules and Restrictions": "Trade Issue",
    "Chart Access": "Platform Issue",
    "Chart Access and Usage": "Platform Issue",
    // Competition
    "Competition Registration Issue": "Competition Issue",
    "Competition Rewards": "Competition Issue",
    "Competition Rules": "Competition Issue",
    // Consistency & Copy Trading
    "Consistency Rule": "Trade Issue",
    "Consistency Rule and Contract Limits": "Trade Issue",
    "Consistency Rules": "Trade Issue",
    "Consistency Rules and Account Types": "Trade Issue",
    "Consistency Score Requirement": "Trade Issue",
    "Copy Trading": "Restriction Related Issue",
    "Copy Trading and Account Merging": "Restriction Related Issue",
    "Copy Trading Policy": "Restriction Related Issue",
    "Copy Trading Rules": "Restriction Related Issue",
    "Country Restrictions": "Restriction Related Issue",
    "Coupon Redemption Issue": "Coupon Code related issue",
    "Credentials after payout": "Payout related issue",
    "Current Offers Inquiry": "Offer Related Query",
    // Deposits & Discounts
    "Deposit Issues": "Other Payment Issues",
    "Deposit Options": "Other Payment Issues",
    "Disciplined Trader Program": "Account Related Issue",
    "Discount Application": "Discount related issue",
    "Discount Coupon Code": "Coupon Code related issue",
    // "Discount Inquiry" moved to QUERY_TOPIC_MAPPING
    "Discount Offers": "Discount related issue",
    "Discounts": "Discount related issue",
    "Discounts & Coupons": "Coupon Code related issue",
    "Discounts & Offers": "Discount related issue",
    "Discounts and Account Reset": "Discount related issue",
    "Discounts and Promotions": "Discount related issue",
    // Documents & KYC
    "Document Acceptance": "KYC_Issue",
    "Document Requirements": "KYC_Issue",
    "Document Submission and Verification": "KYC_Issue",
    "Document Upload Issues": "KYC_Issue",
    "Document Verification": "KYC_Issue",
    "Drawdown Calculation": "Trade Issue",
    // EA & Expert Advisors
    "EA Usage": "Restriction Related Issue",
    "EA Usage and Restrictions": "Restriction Related Issue",
    "EA Usage Rules": "Restriction Related Issue",
    "Expert Advisor usage": "Restriction Related Issue",
    "Expert Advisors (EAs) and Trading Rules": "Restriction Related Issue",
    "Expert Advisors (EAs) and VPS usage": "Restriction Related Issue",
    "Expert Advisors (EAs) usage": "Restriction Related Issue",
    // Free Trial
    "Free Account Offers": "Offer Related Query",
    "Free Trial": "Offer Related Query",
    "Free Trial Account": "Offer Related Query",
    "Free Trial and Rewards": "Offer Related Query",
    "Free Trial Explanation": "Offer Related Query",
    "Funding Account Issues": "Account Related Issue",
    // Futures
    "Futures": "Trade Issue",
    "Futures Account Guidelines": "Trade Issue",
    "Futures Account Rules and Performance Rewards": "Trade Issue",
    "Futures and CFDs usage restrictions": "Restriction Related Issue",
    "Futures Challenge and Payouts": "Trade Issue",
    "Futures Challenge and Platform Access": "Platform Issue",
    "Futures EOD system": "Trade Issue",
    "Futures Leverage Information": "Trade Issue",
    "Futures Payout Split": "Payout related issue",
    "Futures Performance Reward": "Payout related issue",
    "Futures Plan and Profit Rules": "Trade Issue",
    "Futures Positions Limits": "Trade Issue",
    "Futures Trading": "Trade Issue",
    "Futures Trading and Data Activation": "Trade Issue",
    "Futures Trading Education": "Trade Issue",
    "Futures Trading Hours": "Trade Issue",
    "Futures Trading Instruments": "Trade Issue",
    "Futures Trading Platform Usage": "Platform Issue",
    "Futures Trading Restrictions": "Restriction Related Issue",
    "Futures Trading Rules": "Trade Issue",
    // General
    // "General Inquiry" moved to QUERY_TOPIC_MAPPING
    "General Queries": "Random Issues",
    "Geographical Restrictions": "Restriction Related Issue",
    "Identity Verification": "KYC_Issue",
    "Infinity Points TikTok Rewards": "Offer Related Query",
    "Initial Contact": "Random Issues",
    "Instant Funding Account Rules": "Trade Issue",
    "Instruments Information": "Trade Issue",
    "IP and Device Usage Policy": "Restriction Related Issue",
    // KYC
    "KYC & Verification": "KYC_Issue",
    "KYC Issue": "KYC_Issue",
    "KYC process and eligibility": "KYC_Issue",
    "KYC Process and Requirements": "KYC_Issue",
    "KYC Process Delay": "KYC_Issue",
    "KYC Process Duration": "KYC_Issue",
    "KYC Process Information": "KYC_Issue",
    "KYC Processing Time": "KYC_Issue",
    "KYC Status and Dashboard Update": "KYC_Issue",
    "KYC status update": "KYC_Issue",
    "KYC Verification": "KYC_Issue",
    "Language Support": "Random Issues",
    "Legacy Account Rules": "Trade Issue",
    // Leverage & Margin
    "Leverage and Consistency Rules": "Trade Issue",
    "Leverage and Margin": "Trade Issue",
    "Leverage Information": "Trade Issue",
    "Login Issues": "Login_Issue",
    "Loss Limits and Account Types": "Trade Issue",
    "Manual KYC Verification": "KYC_Issue",
    "Margin and Risk Rules": "Trade Issue",
    "Margin Requirements": "Trade Issue",
    "Margin Rules": "Trade Issue",
    "Margin Rules and Risk Limits": "Trade Issue",
    "Margin Usage Violation": "Trade Issue",
    "Margin Violation and Account Termination": "Trade Issue",
    "Name Change Request": "Account Related Issue",
    "Offers & Coupons": "Offer Related Query",
    "Others": "Random Issues",
    "Password Recovery": "Password issue",
    // Payment
    "Payment Confirmation": "Other Payment Issues",
    "Payment Issues": "Other Payment Issues",
    "Payment Method Declined": "Other Payment Issues",
    "Payment Methods": "Other Payment Issues",
    "Payment Transaction Inquiry": "Other Payment Issues",
    "Payment Verification": "Other Payment Issues",
    "Payment Verification and Account Access Delay": "Other Payment Issues",
    "Payment Verification and Account Activation": "Other Payment Issues",
    // Payout & Withdrawal
    "Payout": "Payout related issue",
    "Payout Caps and Withdrawal Limits": "Payout related issue",
    "Payout Eligibility": "Payout related issue",
    "Payout Eligibility and Schedule": "Payout related issue",
    "Payout Inquiry": "Payout related issue",
    "Payout Process": "Payout related issue",
    "Payout Process and Rules": "Payout related issue",
    "Payout Related Issues": "Payout related issue",
    "Payout Rules": "Payout related issue",
    "Performance Reward Payouts": "Payout related issue",
    // Platform
    "Platform & Account Model Switch Request": "Platform Issue",
    "Platform Access and Setup": "Platform Issue",
    "Platform Access Issues": "Platform Issue",
    "Platform Usage": "Platform Issue",
    "Product Information": "Random Issues",
    // Promotions
    "Promotion Eligibility": "Offer Related Query",
    "Promotion Terms and Eligibility": "Offer Related Query",
    "Promotions": "Offer Related Query",
    "Promotions Eligibility": "Offer Related Query",
    "Refer & Earn Program": "Commission",
    // Refund
    "Refund Policy": "Refund Related Issue",
    "Refund Process": "Refund Related Issue",
    "Refund Request": "Refund Related Issue",
    "Refund Request and Account Reactivation": "Refund Related Issue",
    // Restrictions
    "Restricted Strategies": "Restriction Related Issue",
    "Restricted Trading Strategies": "Restriction Related Issue",
    "Reward Details": "Competition Issue",
    "Reward Eligibility and Terms": "Competition Issue",
    "Reward Offers": "Offer Related Query",
    "Rewards and Promotions": "Offer Related Query",
    // Risk & Rules
    "Risk Management": "Trade Issue",
    "Risk Management / Stop Loss Policy": "Trade Issue",
    "Risk Management Guidelines": "Trade Issue",
    "Rules & Scaling": "Trade Issue",
    "Scaling and Maximum Drawdown": "Trade Issue",
    "Scaling Conditions and Account Rules": "Trade Issue",
    "Scaling Program and Funding Limits": "Trade Issue",
    "Scaling Up Capital": "Trade Issue",
    "Subscriptions and Account Models": "Account Related Issue",
    "Supported Platforms": "Platform Issue",
    "Tax Documents": "Payout related issue",
    "Technical Issue": "Tech Issue",
    "Tools & Features": "Platform Issue",
    "Trade Execution & Rules": "Trade Issue",
    "Trading Bots Usage Policy": "Restriction Related Issue",
    "Trading Competition": "Competition Issue",
    "Trading Competition Registration": "Competition Issue",
    "Trading Ethics & Standards": "Restriction Related Issue",
    "Trading Ethics Review": "Restriction Related Issue",
    "Trading Hours and Restrictions": "Trade Issue",
    "Trading Instruments": "Trade Issue",
    "Trading Mechanics": "Trade Issue",
    "Trading Restrictions and Account Features": "Restriction Related Issue",
    "Trading Rules": "Trade Issue",
    "Trading Rules & Challenges": "Trade Issue",
    "Trading Rules and Account Features": "Trade Issue",
    "Trading Rules and Margin Management": "Trade Issue",
    "Trading Rules and Policies": "Trade Issue",
    "Trading Rules and Restrictions": "Trade Issue",
    "Trading Rules and Risk Management": "Trade Issue",
    "Trading Rules Clarification": "Trade Issue",
    "Trading Rules Violation Explanation": "Trade Issue",
    // 2FA & Auth
    "Two-Factor Authentication": "Tech Issue",
    "Two-Factor Authentication (2FA) and Login Issues": "Tech Issue",
    "Two-Factor Authentication (2FA) Issue": "Tech Issue",
    "Two-Factor Authentication (2FA) Issues": "Tech Issue",
    "Two-Factor Authentication (2FA) Setup": "Tech Issue",
    "Two-Factor Authentication (2FA) Setup and Access": "Tech Issue",
    "Verification Code Reset": "Tech Issue",
    "Verification Process": "KYC_Issue",
    "VPN/VPS Usage": "Platform Issue",
    // Withdrawal
    "Withdrawal": "Payout related issue",
    "Withdrawal Issues": "Payout related issue",
    "Withdrawal Limits": "Payout related issue",
    "Withdrawal Options": "Payout related issue",
    "Withdrawal Process": "Payout related issue",
    "Withdrawal Process and Limits": "Payout related issue",
    "Withdrawal Rules": "Payout related issue",
    "Withdrawals": "Payout related issue"
};

// Query Topic Mapping - Maps sub-topics to main topics for Query Analysis
// Based on: https://docs.google.com/spreadsheets/d/1n5JXji1xyTwVriysmsQOopMlDM9hfhu7jVAI-q8fzWQ
// Plus additional mappings from actual database sub-topics
export const QUERY_TOPIC_MAPPING = {
    // OFFER RELATED QUERY
    "Halloween Offer": "OFFER RELATED QUERY",
    "Black Friday Offer": "OFFER RELATED QUERY",
    "Christmas Offer": "OFFER RELATED QUERY",
    "New Year Offer": "OFFER RELATED QUERY",
    "Discount Code": "OFFER RELATED QUERY",
    "Promotional Campaign": "OFFER RELATED QUERY",
    "Limited Time Deal": "OFFER RELATED QUERY",
    "Referral Discount": "OFFER RELATED QUERY",
    "Offer Related Query": "OFFER RELATED QUERY",
    "Offer related confusion": "OFFER RELATED QUERY",
    "Halloween Offer Query": "OFFER RELATED QUERY",
    "Giveaway Query": "OFFER RELATED QUERY",
    "Giveaway Claim": "OFFER RELATED QUERY",

    // CHALLENGE SELECTION QUERY
    "Stellar Instant": "CHALLENGE SELECTION QUERY",
    "CFD vs Futures Challenge": "CHALLENGE SELECTION QUERY",
    "Rapid vs Legacy Challenge": "CHALLENGE SELECTION QUERY",

    // PRICING & PAYMENT QUERY
    "Payment Method": "PRICING & PAYMENT QUERY",
    "Registration Fee Refund": "PRICING & PAYMENT QUERY",
    "Refund Policy": "PRICING & PAYMENT QUERY",
    "Facing Payment Error": "PRICING & PAYMENT QUERY",
    "Payment Method Not Available": "PRICING & PAYMENT QUERY",

    // ACCOUNT SETUP QUERY
    "MT5 Access": "ACCOUNT SETUP QUERY",
    "Login Details Not Received": "ACCOUNT SETUP QUERY",
    "Password Reset": "ACCOUNT SETUP QUERY",
    "Platform Download": "ACCOUNT SETUP QUERY",
    "Fundednext Account Query": "ACCOUNT SETUP QUERY",
    "Challenge Account Query": "ACCOUNT SETUP QUERY",

    // CHALLENGE RULES QUERY
    "Profit Target": "CHALLENGE RULES QUERY",
    "Phase 1 Profit Target": "CHALLENGE RULES QUERY",
    "Phase 2 Profit Target": "CHALLENGE RULES QUERY",
    "Funded Account Profit": "CHALLENGE RULES QUERY",
    "Daily Loss Limit": "CHALLENGE RULES QUERY",
    "Maximum Loss Limit": "CHALLENGE RULES QUERY",
    "Daily Loss Reset Time": "CHALLENGE RULES QUERY",
    "Minimum Trading Days": "CHALLENGE RULES QUERY",
    "Trading Day Definition": "CHALLENGE RULES QUERY",
    "Weekend Trading": "CHALLENGE RULES QUERY",
    "Overnight Trade Holding": "CHALLENGE RULES QUERY",
    "Funded Account Rules": "CHALLENGE RULES QUERY",
    "News Trading Allowed": "CHALLENGE RULES QUERY",
    "News Trading Query": "CHALLENGE RULES QUERY",
    "Minimum Trading Days Confusion": "CHALLENGE RULES QUERY",
    "Challenge Rule Clarification": "CHALLENGE RULES QUERY",
    "Competition Rule Clarification": "CHALLENGE RULES QUERY",

    // WITHDRAWAL & PAYOUT QUERY
    "Consistency Rule for Withdrawal": "WITHDRAWAL & PAYOUT QUERY",
    "Withdrawal Delay": "WITHDRAWAL & PAYOUT QUERY",
    "Withdrawal Rejection": "WITHDRAWAL & PAYOUT QUERY",
    "Payout Not Received": "WITHDRAWAL & PAYOUT QUERY",
    "Payment Method Issue": "WITHDRAWAL & PAYOUT QUERY",
    "Payout Method": "WITHDRAWAL & PAYOUT QUERY",
    "Payout Related Query": "WITHDRAWAL & PAYOUT QUERY",
    "Payout Delay Issue": "WITHDRAWAL & PAYOUT QUERY",
    "Payout Discrepancy": "WITHDRAWAL & PAYOUT QUERY",
    "Payout Rejected": "WITHDRAWAL & PAYOUT QUERY",
    "Not Eligible for Payout": "WITHDRAWAL & PAYOUT QUERY",

    // PERFORMANCE REWARD QUERY
    "Minimum Performance Reward": "PERFORMANCE REWARD QUERY",
    "Maximum Performance Reward": "PERFORMANCE REWARD QUERY",

    // PAYOUT CYCLE QUERY
    "First Payout Timeline": "PAYOUT CYCLE QUERY",
    "Subsequent Payout Timing": "PAYOUT CYCLE QUERY",
    "Bi-Weekly Payout": "PAYOUT CYCLE QUERY",
    "On-Demand Payout": "PAYOUT CYCLE QUERY",

    // SCALE-UP PLAN QUERY
    "Scale-Up Requirements": "SCALE-UP PLAN QUERY",
    "Tier Upgrade Criteria": "SCALE-UP PLAN QUERY",
    "Scale-Up Eligibility Inquiry": "SCALE-UP PLAN QUERY",

    // STELLAR INSTANT SCALE-UP QUERY
    "Stellar Instant Scale-Up Rules": "STELLAR INSTANT SCALE-UP QUERY",
    "Tier 1/2/3+ Progression": "STELLAR INSTANT SCALE-UP QUERY",
    "Balance Increase Calculation": "STELLAR INSTANT SCALE-UP QUERY",
    "Trailing Loss Limit Update": "STELLAR INSTANT SCALE-UP QUERY",

    // KYC & VERIFICATION QUERY
    "KYC Submission Timing": "KYC & VERIFICATION QUERY",
    "Required Documents": "KYC & VERIFICATION QUERY",
    "Document Upload Process": "KYC & VERIFICATION QUERY",
    "KYC Approval Duration": "KYC & VERIFICATION QUERY",
    "KYC Rejection Reason": "KYC & VERIFICATION QUERY",
    "Swift KYC": "KYC & VERIFICATION QUERY",
    "KYC Eligibility Inquiry": "KYC & VERIFICATION QUERY",

    // ACCOUNT RESET QUERY
    "Reset Cost": "ACCOUNT RESET QUERY",
    "Reset vs New Purchase": "ACCOUNT RESET QUERY",
    "Reset Discount": "ACCOUNT RESET QUERY",
    "Reset Account Timeline": "ACCOUNT RESET QUERY",
    "Reset Eligibility": "ACCOUNT RESET QUERY",

    // REFUND RELATED QUERY
    "Refund Delay": "REFUND RELATED QUERY",
    "Confirmo Refund Issue": "REFUND RELATED QUERY",

    // COUPON & DISCOUNT QUERY
    "Coupon Code Not Working": "COUPON & DISCOUNT QUERY",
    "Coupon Not Available": "COUPON & DISCOUNT QUERY",
    "Forgot to Apply Coupon": "COUPON & DISCOUNT QUERY",
    "Looking for coupon code": "COUPON & DISCOUNT QUERY",
    "No Personal Coupon": "COUPON & DISCOUNT QUERY",
    "Unhappy with Coupon Perks": "COUPON & DISCOUNT QUERY",
    "Unsatisfied with Discount": "COUPON & DISCOUNT QUERY",

    // AI-generated inquiry sub-topics
    "Discount Inquiry": "COUPON & DISCOUNT QUERY",
    "General Inquiry": "ACCOUNT SETUP QUERY",
    "Payout Process Inquiry": "WITHDRAWAL & PAYOUT QUERY",
    "Performance Reward Inquiry": "PERFORMANCE REWARD QUERY",
    "Promotions Inquiry": "OFFER RELATED QUERY",

    // CHALLENGE SELECTION QUERY (missing from prompt)
    "Best Challenge Recommendation": "CHALLENGE SELECTION QUERY",
    "Challenge Upgrade/Downgrade": "CHALLENGE SELECTION QUERY",
    "Challenge Pricing": "CHALLENGE SELECTION QUERY",

    // PRICING & PAYMENT QUERY (missing from prompt)
    "Payment Failure": "PRICING & PAYMENT QUERY",
    "Incorrect Charge": "PRICING & PAYMENT QUERY",
    "Invoice Request": "PRICING & PAYMENT QUERY",
    "Coupon Not Applied": "COUPON & DISCOUNT QUERY",

    // ACCOUNT SETUP QUERY (missing from prompt)
    "Server Selection": "ACCOUNT SETUP QUERY",
    "Account Credentials Invalid": "ACCOUNT SETUP QUERY",
    "VPN Allowed": "ACCOUNT SETUP QUERY",
    "IP Change": "ACCOUNT SETUP QUERY",
    "Multiple Locations": "ACCOUNT SETUP QUERY",
    "IP Flagged": "ACCOUNT SETUP QUERY",
    "General Information": "ACCOUNT SETUP QUERY",
    "Feature Request": "ACCOUNT SETUP QUERY",
    "Feedback": "ACCOUNT SETUP QUERY",

    // CHALLENGE RULES QUERY (missing from prompt + seen in DB)
    "Challenge Rules Query": "CHALLENGE RULES QUERY",
    "Consistency Rule Inquiry": "CHALLENGE RULES QUERY",
    "Funded Account Profit": "CHALLENGE RULES QUERY",
    "Trading Days Requirement": "CHALLENGE RULES QUERY",
    "Inactivity Rule": "CHALLENGE RULES QUERY",
    "News Trading Rule": "CHALLENGE RULES QUERY",
    "Weekend Holding Rule": "CHALLENGE RULES QUERY",
    "Maximum Loss Limit Explanation": "CHALLENGE RULES QUERY",
    "Policy Clarification": "CHALLENGE RULES QUERY",
    "Trading Restrictions": "CHALLENGE RULES QUERY",
    // Copy Trading Query (mapped to CHALLENGE RULES QUERY)
    "Copy Trading Allowed": "CHALLENGE RULES QUERY",
    "Own Account Copy Trading": "CHALLENGE RULES QUERY",
    "Third-Party Copying": "CHALLENGE RULES QUERY",
    "Trade Copier Tool": "CHALLENGE RULES QUERY",
    "Cloud-Based Copier": "CHALLENGE RULES QUERY",
    "VPS Trade Copier": "CHALLENGE RULES QUERY",
    "Master-Slave Setup": "CHALLENGE RULES QUERY",
    // Prohibited Strategies Query
    "Prohibited Strategy List": "CHALLENGE RULES QUERY",
    "High Frequency Trading": "CHALLENGE RULES QUERY",
    "Scalping": "CHALLENGE RULES QUERY",
    "Grid Trading": "CHALLENGE RULES QUERY",
    "Hedging": "CHALLENGE RULES QUERY",
    "Gambling Behavior": "CHALLENGE RULES QUERY",
    "Arbitrage": "CHALLENGE RULES QUERY",
    "Tick Scalping": "CHALLENGE RULES QUERY",
    "Martingale": "CHALLENGE RULES QUERY",
    // EA & Robot Query
    "EA Allowed": "CHALLENGE RULES QUERY",
    "Free EA": "CHALLENGE RULES QUERY",
    "Paid EA": "CHALLENGE RULES QUERY",
    "EA Modification": "CHALLENGE RULES QUERY",
    "EA to Manual Switch": "CHALLENGE RULES QUERY",
    // News Trading Query
    "Restricted News Events": "CHALLENGE RULES QUERY",
    "News Violation": "CHALLENGE RULES QUERY",
    // Funded Account Query (rule side)
    "Funded Account Disabled": "CHALLENGE RULES QUERY",

    // WITHDRAWAL & PAYOUT QUERY (missing from prompt)
    "First Payout": "WITHDRAWAL & PAYOUT QUERY",
    "Minimum Payout": "WITHDRAWAL & PAYOUT QUERY",
    "Profit Split": "WITHDRAWAL & PAYOUT QUERY",
    "Funded Account Breach": "WITHDRAWAL & PAYOUT QUERY",

    // SCALE-UP PLAN QUERY (missing from prompt)
    "Scale-Up Timeline": "SCALE-UP PLAN QUERY",
    "Scale-Up Percentage": "SCALE-UP PLAN QUERY",
    "Funded Account Upgrade": "SCALE-UP PLAN QUERY",

    // STELLAR INSTANT SCALE-UP QUERY (missing from prompt)
    "Instant Scaling Rules": "STELLAR INSTANT SCALE-UP QUERY",
    "Instant Scale-Up Missing": "STELLAR INSTANT SCALE-UP QUERY",

    // PAYOUT CYCLE QUERY (missing from prompt)
    "Payout Schedule": "PAYOUT CYCLE QUERY",
    "Missed Payout Cycle": "PAYOUT CYCLE QUERY",
    "Early Payout Request": "PAYOUT CYCLE QUERY",

    // PERFORMANCE REWARD QUERY (missing from prompt)
    "Performance Bonus": "PERFORMANCE REWARD QUERY",
    "Reward Calculation": "PERFORMANCE REWARD QUERY",
    "Missing Reward": "PERFORMANCE REWARD QUERY",

    // KYC & VERIFICATION QUERY (missing from prompt)
    "KYC Required": "KYC & VERIFICATION QUERY",
    "KYC Rejected": "KYC & VERIFICATION QUERY",
    "KYC Pending": "KYC & VERIFICATION QUERY",
    "Document Upload Issue": "KYC & VERIFICATION QUERY",
    "Name Mismatch": "KYC & VERIFICATION QUERY",

    // ACCOUNT RESET QUERY (missing from prompt)
    "Paid Reset": "ACCOUNT RESET QUERY",
    "Reset Not Applied": "ACCOUNT RESET QUERY",
    "Reset Rules": "ACCOUNT RESET QUERY",

    // FLEX Query — informational questions about FundedNext Futures FLEX
    // (what FLEX is, pricing, rules, eligibility, account sizes, launch date,
    // FLEX vs Rapid/Legacy/Bolt, whether FLEX is CFD or Futures).
    // Main = Sub = "FLEX Query" by design.
    "FLEX Query": "FLEX Query"
};

// List of all Query Main Topics for dropdowns
export const QUERY_MAIN_TOPICS = [
    "OFFER RELATED QUERY",
    "CHALLENGE SELECTION QUERY",
    "PRICING & PAYMENT QUERY",
    "REFUND RELATED QUERY",
    "COUPON & DISCOUNT QUERY",
    "ACCOUNT SETUP QUERY",
    "CHALLENGE RULES QUERY",
    "WITHDRAWAL & PAYOUT QUERY",
    "PERFORMANCE REWARD QUERY",
    "PAYOUT CYCLE QUERY",
    "SCALE-UP PLAN QUERY",
    "STELLAR INSTANT SCALE-UP QUERY",
    "KYC & VERIFICATION QUERY",
    "ACCOUNT RESET QUERY",
    "FLEX Query"
];

// Utilities for chart calculations
export const topNWithOther = (data, topN = 5) => {
    // ... logic if needed, or keeping it strictly for export
    return [];
};
export const calculatePercentages = () => { };
